name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - CONTRIBUTING.md
      - LICENSE
      - README.md
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz
        python -m pip install --upgrade pip
        pip install pytest pytest-cov graphviz black pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Format code with Black
      run: black .
      
    - name: Analysing the code with pylint
      run: |
        pylint $(find seealgo -name '*.py')
      
    - name: Test
      run: |
        pytest --cov=./ --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: false
